### ISSUE TITLE
layout not found

### ISSUE THREAD

**Issue by rickysut** [liberu-crm/crm-laravel#100]
This is  a **bug**. 

### Prerequisites
* [ yes ] Are you running the latest version?
* [ yes ] Are you reporting to the correct repository?
* [ yes ] Did you check the documentation?
* [ yes ] Did you perform a cursory search?

### Description

i just install this repo and when I run 127.0.0.1:8000/app it show

InvalidArgumentException
View [layouts.home] not found.

### Steps to Reproduce
php artisan serve

### Expected behavior
login screen

### Actual behavior
ERROR layout/home.blade.php not found

**Comment by curtisdelicata** [comment]
Will be fixed when the major fixes to Jetstream and auth with teams on real estate project is merged into all projects. Maybe early in the week. Thanks for the report.

**Comment by curtisdelicata** [comment]
Fixed.
