### ISSUE TITLE
Code errors

### ISSUE THREAD

**Issue by psad73** [liberu-crm/crm-laravel#240]
### Details

app/Http/Controllers/LeadFormController.php:11 - php again?
app/Http/Livewire/OpportunityPipeline.php:45
tests/Feature/CustomFieldsTest.php:180 
tests/Unit/GoogleCalendarServiceTest.php:134 - second class declaration?
tests/Unit/LeadTest.php:104
tests/Unit/TwilioServiceTest.php:84
app/Http/Livewire/CreateTeam.php:9 - "Can not redeclare CreateTeam class"??

VisualCode highlights only these. Are there any other, not so obvious errors as well?

**Comment by curtisdelicata** [comment]
Thank you for letting us know. Pull requests are welcome
